stages:
  filter_by_frequency:
    cmd: python3 src/data/filter_by_frequency.py
    deps:
    - data/raw/loc-brightkite_totalCheckins.txt
    - src/data/filter_by_frequency.py
    params:
    - filter.required_unique_places
    - filter.required_unique_visitors
    outs:
    - data/interim/filtered_by_frequency.csv
  categorize_geoposition:
    cmd: python3 src/features/categorize_geoposition.py
    deps:
    - data/interim/filtered_by_frequency.csv
    - src/features/categorize_geoposition.py
    params:
    - geoposition.round_precision
    outs:
    - data/interim/categorical_geoposition.csv
  label_encode:
    cmd: python3 src/features/label_encode.py
    deps:
    - data/interim/categorical_geoposition.csv
    - data/interim/filtered_by_frequency.csv
    - src/features/label_encode.py
    outs:
    - artifacts/label_encoders.pkl
    - data/interim/label_encoded.csv
  group_and_compute_distances:
    cmd: python3 src/features/group_and_compute_distances.py
    deps:
    - data/interim/label_encoded.csv
    - src/features/group_and_compute_distances.py
    outs:
    - data/interim/grouped_by_user_with_distances.csv
  split_data:
    cmd: python3 src/features/split_data.py
    deps:
    - data/interim/grouped_by_user_with_distances.csv
    - src/features/split_data.py
    params:
    - split.random_state
    - split.test_size
    outs:
    - data/processed/test.csv
    - data/processed/train.csv
  train_lstm:
    cmd: python3 src/models/lstm/train.py
    deps:
    - artifacts/label_encoders.pkl
    - data/processed/train.csv
    - src/models/lstm/data.py
    - src/models/lstm/model.py
    - src/models/lstm/train.py
    params:
    - lstm
    outs:
    - artifacts/lstm.ckpt:
        checkpoint: true
    live:
      logs:
        summary: true
        html: true
  split_data_by_time:
    cmd: python3 src/features/split_data_by_time.py
    deps:
    - data/interim/grouped_by_user_with_distances.csv
    - src/features/split_data_by_time.py
    params:
    - split.time_based_train_size
    outs:
    - data/interim/time_based_split_test.csv
    - data/interim/time_based_split_train.csv
