filter:
  required_unique_visitors: 10
  required_unique_places: 5

geoposition:
  round_precision: 2

split:
  test_size: 0.3
  random_state: 0

lstm:
  data:
    max_sequence_length: 100
    batch_size_train: 4
    batch_size_valid: 32
  model:
    embedding_dim: 64
    hidden_dim: 64
    num_layers: 1
    dropout: 0.
  optimizer:
    learning_rate: 1e-3
