filter:
  required_unique_visitors: 10
  required_unique_places: 5

geoposition:
  round_precision: 2

split:
  test_size: 0.3
  random_state: 0
  time_based_train_size: 0.8

lstm:
  data:
    max_sequence_length: 100
    batch_size_train: 16
    batch_size_valid: 64
  model:
    embedding_dim: 64
    hidden_dim: 64
    num_layers: 3
    dropout: 0.
  optimizer:
    learning_rate: 1e-3
    epochs: 200
