version: '3.4'

services:
  backend:
    build:
      context: ./
      dockerfile: ./dockerfiles/backend
    networks:
      - common
    ports:
      - "8001:8001"
    volumes:
      - ./footage:/footage
  frontend:
    build:
      context: ./
      dockerfile: ./dockerfiles/nginx
    networks:
      - common
    depends_on:
      - "backend"
    ports:
      - "80:80"
    volumes:
      - ./footage:/footage
  # worker:
  #   build:
  #     context: ./worker
  #     dockerfile: ../dockerfiles/worker
  #   ports:
  #     - "8002:8002"
  #   networks:
  #     - common
networks:
  common:
